TicariOtomasyonProjesi/TicariOtomasyonProjesi/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyonProjesi.Models.Siniflar;

namespace TicariOtomasyonProjesi.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var liste = c.Faturalars.ToList();
            return View(liste);
        }


        [HttpGet]
        public ActionResult FaturaEkle()
        {

            return View();
        }

        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturalars.Find(id);
            return View("FaturaGetir", fatura);

        }

        public ActionResult FaturaGuncelle(Faturalar f)
        {

            var fatura = c.Faturalars.Find(f.Faturaid);
            fatura.FaturaSeriNo = f.FaturaSeriNo;
            fatura.FaturaSıraNo = f.FaturaSıraNo;
            fatura.Saat = f.Saat;
            fatura.Tarih = f.Tarih;
            fatura.TeslimAlan = f.TeslimAlan;
            fatura.TeslimEden = f.TeslimEden;
            fatura.VergiDairesi = f.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaDetay(int id)
        {
            var degerler = c.FaturaKalems.Where(x => x.Faturaid == id).ToList();
           
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem p)
        {
            c.FaturaKalems.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Dinamik()
        {
            Class4 cs = new Class4();
            cs.deger1 = c.Faturalars.ToList();
            cs.deger2 = c.FaturaKalems.ToList();
            return View(cs);
        }

        public ActionResult FaturaKaydet(string FaturaSeriNo, string FaturaSıraNo, DateTime Tarih, string VergiDairesi, string Saat,
            string TeslimEden, string TeslimAlan, string Toplam, FaturaKalem[] kalemler)
        {

            Faturalar f = new Faturalar();
            f.FaturaSeriNo = FaturaSeriNo;
            f.FaturaSıraNo = FaturaSıraNo;
            f.Tarih = Tarih;
            f.VergiDairesi = VergiDairesi;
            f.Saat = Saat;
            f.TeslimEden = TeslimEden;
            f.TeslimAlan = TeslimAlan;
            f.Toplam = decimal.Parse(Toplam);
            c.Faturalars.Add(f);
            foreach (var x in kalemler)
            {
                FaturaKalem fk = new FaturaKalem();
                fk.Aciklama = x.Aciklama;
                fk.BirimFiyat = x.BirimFiyat;
                fk.Miktar = x.Miktar;
                fk.Faturaid = x.FaturaKalemid;
                fk.Tutar = x.Tutar;
                c.FaturaKalems.Add(fk);

            }
            c.SaveChanges();
            return Json("İşlem Başarılı", JsonRequestBehavior.AllowGet);
        }
    }
}

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using TicariOtomasyonProjesi.Models.Siniflar;

namespace TicariOtomasyonProjesi.Controllers
{
    public class KategoriController : Controller
    {
        Context c = new Context();
        // GET: Kategori
        public ActionResult Index(int sayfa=1)
        {
            var degerler = c.Kategoris.ToList().ToPagedList(sayfa,9);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {

            return View();
        }

        [HttpPost]
        public ActionResult KategoriEkle(Kategori k)
        {

            c.Kategoris.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriSil(int id)
        {
            var ktg = c.Kategoris.Find(id);
            c.Kategoris.Remove(ktg);
            c.SaveChanges();
            return RedirectToAction("Index");


        }

        public ActionResult KategoriGetir(int id)
        {

            var kategori = c.Kategoris.Find(id);
            return View("KategoriGetir", kategori);
        }

        public ActionResult KategoriGuncelle(Kategori k)
        {
            var ktgr = c.Kategoris.Find(k.KategoriID);
            ktgr.KategoriAd = k.KategoriAd;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

       
    }
}

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Shared/AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Ticari Otomasyon Sitesi</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/Kategori/Index">Ticari Otomasyon</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Ara..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Ayarlar</a>
                    <a class="dropdown-item" href="#">Hesabım</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/CariPanel/LogOut">Çıkış</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İşlemler</div>
                        <a class="nav-link" href="/Kategori/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="/Urun/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-flask"></i></div>
                            Ürünler
                        </a>
                        <a class="nav-link" href="/Departman/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
                            Departmanlar
                        </a>
                        <a class="nav-link" href="/Cari/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Cariler
                        </a>






                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-lock"></i></div>
                            Admin
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Yetkilendirme
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="/login/Index/">Giriş Yap</a>
                                        <a class="nav-link" href="/login/Index/">Kayıt Ol</a>
                                        <a class="nav-link" href="/login/Index/"> Şifremi Unuttum</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Hata Sayfası
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">


                                    <a class="nav-link" href="/Error/PageError/">404 Page</a>


                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Rapor & Fatura</div>

                        <a class="nav-link" href="/Satis/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-paperclip"></i></div>
                            Satışlar
                        </a>

                        <a class="nav-link" href="/Fatura/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
                            Faturalar
                        </a>

                        <a class="nav-link" href="/Fatura/Dinamik">
                            <div class="sb-nav-link-icon"><i class="fas fa-procedures"></i></div>
                            Dinamik Faturalar
                        </a>
                        <a class="nav-link" href="/Personel/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Personel Listesi
                        </a>

                        <a class="nav-link" href="/Personel/PersonelListe">
                            <div class="sb-nav-link-icon"><i class="fas fa-people-carry"></i></div>
                            Personel Bilgileri
                        </a>

                     

                        <a class="nav-link" href="/Urun/UrunListesi">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Pdf-Exel
                        </a>
                        <a class="nav-link" href="/QR/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            QR Üret
                        </a>

                        <a class="nav-link" href="/istatistik/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-pager"></i></div>
                            İstatistikler
                        </a>

                        <a class="nav-link" href="/Galeri/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-laptop"></i></div>
                            Galeri
                        </a>

                        <a class="nav-link" href="/Yapilacak/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-phone"></i></div>
                            Yapılacaklar
                        </a>

                        @*<a class="nav-link" href="/UrunDetay/Index">
           <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
          Ürün Detay
        </a>*@

                        <a class="nav-link" href="/istatistik/KolayTablolar">
                            <div class="sb-nav-link-icon"><i class="fas fa-eye"></i></div>
                            Hızlı Bakış
                        </a>

                        <a class="nav-link" href="/Kargo/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Kargolar
                        </a>


                    </div>
                </div>
                <br /> <br />
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Shared/_Carilayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Ticari Otomasyon Sitesi</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Ticari Otomasyon</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Ara..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="/CariPanel/Index/">Ayarlar</a>
                    <a class="dropdown-item" href="/CariPanel/Index/">Hesabım</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/CariPanel/LogOut/">Çıkış</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Cari Panel Menüsü</div>
                        <a class="nav-link" href="/CariPanel/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-person-booth"></i></div>
                            Profilim
                        </a>
                        <a class="nav-link" href="/CariPanel/Siparislerim">
                            <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                            Siparişlerim
                        </a>
                        <a class="nav-link" href="/CariPanel/KargoTakip/">
                            <div class="sb-nav-link-icon"><i class="fas fa-truck"></i></div>
                            Kargo Takibi
                        </a>
                        <a class="nav-link" href="/CariPanel/GelenMesajlar/">
                            <div class="sb-nav-link-icon"><i class="fas fa-mail-bulk"></i></div>
                           Mesajlar
                        </a>
                        <a class="nav-link" href="/CariPanel/LogOut/">
                            <div class="sb-nav-link-icon"><i class="fas fa-mars"></i></div>
                            Çıkış Yap
                        </a>
                    </div>
                </div>
               
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fatura İşlemleri", "Dinamik", "Fatura", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Faturalar", "Dinamik", "Fatura")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Yardım", "Yardım", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>