TicariOtomasyonProjesi/TicariOtomasyonProjesi/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyonProjesi.Models.Siniflar;

namespace TicariOtomasyonProjesi.Controllers
{
    public class CariController : Controller
    {
        Context c = new Context();
        // GET: Cari
        public ActionResult Index()
        {
            var degerler = c.Carilers.Where(x=>x.Durum==true).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniCari()
        {

            return View();
        }

        [HttpPost]
        public ActionResult YeniCari(Cariler p)
        {
            p.Durum = true;
            c.Carilers.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariSil(int id)
        {
            var cr = c.Carilers.Find(id);
            cr.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariGetir(int id)
        {
            var cari = c.Carilers.Find(id);
            return View("CariGetir", cari);

        }

        public ActionResult CariGuncelle(Cariler p)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }

            var cari = c.Carilers.Find(p.Cariid);
            cari.CariAd = p.CariAd;
            cari.CariSoyad = p.CariSoyad;
            cari.CariSehir = p.CariSehir;
            cari.CariMail = p.CariMail;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult MusteriSatis(int id)
        {

            var degerler = c.SatisHarekets.Where(x => x.Cariid == id).ToList();
            var cr = c.Carilers.Where(x => x.Cariid == id).Select(y => y.CariAd +" "+ y.CariSoyad).FirstOrDefault();
            ViewBag.cari = cr;
            return View(degerler);
        }
    }
}

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Cari/CariGetir.cshtml
@model TicariOtomasyonProjesi.Models.Siniflar.Cariler
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Cari Güncelleme Ekranı</h2> 
<br />
@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post))
{

<div class="form-group">
    @Html.HiddenFor(x => x.Cariid)
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAd, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSoyad, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />
    <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>

</div>



}

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Cari/Index.cshtml
@using TicariOtomasyonProjesi.Models.Siniflar
@model List<Cariler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-striped" style="background-color: #ffffff">
    <tr>
        <th>  Cari Id  </th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail Adresi</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Cariid</td>
            <td>@x.CariAd</td>
            <td>@x.CariSoyad</td>
            <td>@x.CariSehir</td>
            <td>@x.CariMail</td>
            <td><a href="/Cari/CariSil/@x.Cariid" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/CariGetir/@x.Cariid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Cari/Musterisatis/@x.Cariid" class="btn btn-default" style="background-color:lightgreen">Satış Geçmişi</a></td>


        </tr>
    }
</table>
<a href="/Cari/YeniCari/" class="btn btn-info">Yeni cari Ekle</a>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Cari/MusteriSatis.cshtml
@using TicariOtomasyonProjesi.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">
        Cari Adı :  <b> @ViewBag.cari</b>

    </li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>  Satış ID  </th>
        <th>   Ürün </th>
        <th>Personel</th>
        <th>   Fiyat </th>
        <th>  Adet  </th>
        <th>  Toplam  </th>
        <th>  Tarih  </th>
        <th>Yazdır</th>


    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Urun.UrunAd</td>
           <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>




        </tr>
    }
</table>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/Cari/YeniCari.cshtml
@model TicariOtomasyonProjesi.Models.Siniflar.Cariler
@{
    ViewBag.Title = "YeniCari";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<hr />
<h2>Yeni Cari Ekle</h2>
<hr />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />
    <button onclick="fnctn1()" class="btn btn-info">Kaydet</button>
</form>
<script>
    function fnctn1() {
        alert('Cari Eklendi')
    }
</script>