TicariOtomasyonProjesi/TicariOtomasyonProjesi/Controllers/istatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyonProjesi.Models.Siniflar;

namespace TicariOtomasyonProjesi.Controllers
{
    public class istatistikController : Controller
    {
        // GET: istatistik
        Context c = new Context();
        public ActionResult Index()
        {
            var deger1 = c.Carilers.Count().ToString();
            ViewBag.d1 = deger1;
            var deger2 = c.Uruns.Count().ToString();
            ViewBag.d2 = deger2;
            var deger3 = c.Personels.Count().ToString();
            ViewBag.d3 = deger3;
            var deger4 = c.Kategoris.Count().ToString();
            ViewBag.d4 = deger4;
            var deger5 = c.Uruns.Sum(x=>x.Stok).ToString();
            ViewBag.d5 = deger5;
            //ürünler içinden markaları "farklı olanları" seç sayısını yaz
            var deger6 = (from x in c.Uruns select x.Marka).Distinct().Count().ToString();
            ViewBag.d6 = deger6;
            var deger7 = c.Uruns.Count(x=>x.Stok<=10).ToString();
            ViewBag.d7 = deger7;

            //orderby ile sırala descending ile küçükten büyüğe sırala firstordefault ile yakala select ile seç ve yaz
            var deger8 = (from x in c.Uruns orderby x.SatisFiyat descending select x.UrunAd).FirstOrDefault();
            ViewBag.d8 = deger8;

            //orderby ile sırala ascending büyükten küçüğe sırala firstordefault ile yakala select ile seç ve yaz
            var deger9 = (from x in c.Uruns orderby x.SatisFiyat ascending select x.UrunAd).FirstOrDefault();
            ViewBag.d9 = deger9;
            var deger10 = c.Uruns.Count(x=>x.UrunAd=="Cep Telefonu").ToString();
            ViewBag.d10 = deger10;
            var deger11 = c.Uruns.Count(x=>x.UrunAd=="Ipad").ToString();
            ViewBag.d11 = deger11;

            //ürünleri markasına göre grupla, her grubu count olarak büyükten küçüğe sırala,ismi  en çok geçeni seç
            var deger12 = c.Uruns.GroupBy(x => x.Marka).OrderByDescending(y => y.Count()).Select(z => z.Key).FirstOrDefault();
            ViewBag.d12 = deger12;

            //satışharekets içindekileri ürünid ye göre gruplandırıp büyükten küçüğe sırala, en büyük olanın id'sine göre adını bul ve seç ve onu bana yazdır
            var deger13 = c.Uruns.Where(x => x.Urunid == (c.SatisHarekets.GroupBy(y => y.Urunid).OrderByDescending(z => z.Count()).Select(d => d.Key).FirstOrDefault())).Select(k => k.UrunAd).FirstOrDefault();
            ViewBag.d13 = deger13;

            var deger14 = c.SatisHarekets.Sum(x =>x.ToplamTutar).ToString();
            ViewBag.d14 = deger14;

            DateTime bugun = DateTime.Today;
            var deger15 = c.SatisHarekets.Count(x=>x.Tarih==bugun).ToString();
            ViewBag.d15 = deger15;
            var deger16 = c.SatisHarekets.Where(x => x.Tarih == bugun).Sum(y =>(decimal?) y.ToplamTutar).ToString();
            ViewBag.d16 = deger16;
            return View();
        }

        public ActionResult KolayTablolar()
        {
            var sorgu = from x in c.Carilers
                        group x by x.CariSehir into g
                        select new SinifGrup
                        {
                            Sehir = g.Key,
                            Sayi = g.Count()
                        };
            return View(sorgu.ToList());
        }

        public PartialViewResult Partial1()
        {
            var sorgu2 = from x in c.Personels
                         group x by x.Departman.DepartmanAd into g
                         select new SinifGrup2
                         {
                             Departman = g.Key,
                             Sayi = g.Count()
                         };
            return PartialView(sorgu2.ToList());
        }

        public PartialViewResult Partial2()
        {
            var sorgu = c.Carilers.ToList();
            return PartialView(sorgu);
        }

        public PartialViewResult Partial3()
        {
            var sorgu = c.Uruns.ToList();
            return PartialView(sorgu);
        }

        public PartialViewResult Partial4()
        {
            var sorgu2 = from x in c.Uruns
                         group x by x.Marka into g
                         select new SinifGrup3
                         {
                             marka = g.Key,
                             sayi = g.Count()
                         };
            return PartialView(sorgu2.ToList());
        }
    }
}

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/istatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@*renklerin kodlarını https://flatuicolors.com/ sitesinden aldım*@

<!--

Author: W3layouts

Author URL: http://w3layouts.com

License: Creative Commons Attribution 3.0 Unported

License URL: http://creativecommons.org/licenses/by/3.0/

-->

<!DOCTYPE html>

<html>

<head>

    <!-- Custom Theme files -->

    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />

    <!-- Custom Theme files -->

    <script src="~/web2/js/jquery.min.js"></script>

    <link rel="stylesheet" href="~/web2/css/font-awesome.css">

    <!-- Custom Theme files -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,

Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />

    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <!--webfont-->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="js/zingchart.min.js"></script>

    <script src="js/zingchart.jquery.js"></script>

    <script src="js/jquery.easydropdown.js"></script>

    <script src="js/jquery.nicescroll.js"></script>

    <link href="css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />

    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />

    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->

    <script src="~/web2/js/Chart1.js"></script>

    <!-- //chart -->

</head>

<body>

    <div class="total-content" style="; background-color: #f6f6ee">

        <div class="list_of_members">

            <div class="sales" style="background-color:#1abc9c">

                <div class="icon-text">

                    <h3>@ViewBag.d1</h3>

                    <p>Toplam Cari</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">

                    <h3>@ViewBag.d2</h3>

                    <p>Ürün Sayısı</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">

                    <h3>@ViewBag.d3</h3>

                    <p>Personel Sayısı</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">

                    <h3>@ViewBag.d4</h3>

                    <p>Kategori Sayısı</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="clearfix"></div>

        </div>

    </div>

    <div class="clearfix"></div>

    <div class="total-content">

        <div class="list_of_members">

            <div class="sales" style="background-color:#16a085">

                <div class="icon-text">

                    <h3>@ViewBag.d5</h3>

                    <p>Toplam Stok</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">

                    <h3>@ViewBag.d6</h3>

                    <p>Marka Sayısı</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">

                    <h3>@ViewBag.d7</h3>

                    <p>Kritik Seviye</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">

                    <h3>@ViewBag.d8</h3>

                    <p>Max Fiyatlı Ürün</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="clearfix"></div>

        </div>

    </div>

    <div class="clearfix"></div>

    <div class="total-content">

        <div class="list_of_members">

            <div class="sales" style="background-color:#f1c40f">

                <div class="icon-text">

                    <h3>@ViewBag.d9</h3>

                    <p>Min Fiyatlı Ürün</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">

                    <h3>@ViewBag.d12</h3>

                    <p>Max Marka</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">

                    <h3>@ViewBag.d10</h3>

                    <p>Buzdolabı Sayısı</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">

                    <h3>@ViewBag.d11</h3>

                    <p>Laptop Sayısı</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="clearfix"></div>

        </div>

    </div>

    <div class="clearfix"></div>

    <div class="total-content">

        <div class="list_of_members">

            <div class="sales" style="background-color:#f39c12">

                <div class="icon-text">

                    <h3>@ViewBag.d13</h3>

                    <p>En Çok Satan</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">

                    <h3>@ViewBag.d14</h3>

                    <p>Kasadaki Tutar</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">

                    <h3>@ViewBag.d15</h3>

                    <p>Bugünkü Satşlar</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">

                    <h3>@ViewBag.d16</h3>

                    <p>Bugünkü Kasa</p>

                </div>

                <div class="clearfix"></div>

            </div>

            <div class="clearfix"></div>

        </div>

    </div>

</body>

</html>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/istatistik/KolayTablolar.cshtml
@model IEnumerable<TicariOtomasyonProjesi.Models.Siniflar.SinifGrup>
@{
    ViewBag.Title = "KolayTablolar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini" style="; background-color: #f6f6ee">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Basit Tablolar</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Kategori Tablosu</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Kategori Adı</th>
                                            <th>Seviye</th>
                                            <th style="width: 40px">Oran</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1.</td>
                                            <td>Beyaz eşya</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-danger">55%</span></td>
                                        </tr>
                                        <tr>
                                            <td>2.</td>
                                            <td>Küçük ev aletleri</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-warning">70%</span></td>
                                        </tr>
                                        <tr>
                                            <td>3.</td>
                                            <td>Teknolojik Aletler</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-primary">30%</span></td>
                                        </tr>
                                        <tr>
                                            <td>4.</td>
                                            <td>Temizlik Ürünleri</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-success">90%</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer clearfix">
                                <ul class="pagination pagination-sm m-0 float-right">
                                    <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- /.card -->
                        @Html.Action("Partial1", "istatistik")
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Müşteri Şehir Tablosu</h3>

                                <div class="card-tools">

                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Şehir</th>
                                            <th>Seviye</th>
                                            <th style="width: 40px">Adet</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int sirano = 0;}
                                        @foreach (var x in Model)
                                        {


                                            <tr>
                                                <td>@{sirano++;} @sirano</td>
                                                <td>@x.Sehir</td>
                                                <td>
                                                    @if (x.Sayi == 1)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (x.Sayi == 2)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                        </div>
                                                    }
                                                    @if (x.Sayi >= 3)
                                                    {
                                                        <div class="progress progress-xs progress-striped active">
                                                            <div class="progress-bar bg-success" style="width: 90%"></div>
                                                        </div>
                                                    }
                                                </td>
                                                <td>
                                                    @if (x.Sayi == 1)
                                                    {
                                                        <span class="badge bg-danger">@x.Sayi</span>
                                                    }
                                                    @if (x.Sayi == 2)
                                                    {
                                                        <span class="badge bg-warning">@x.Sayi</span>
                                                    }
                                                    @if (x.Sayi == 3)
                                                    {
                                                        <span class="badge bg-success">@x.Sayi</span>
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                        @Html.Action("Partial4","istatistik")
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                @Html.Action("Partial2", "istatistik")
                <!-- /.row -->
                @Html.Action("Partial3", "istatistik")
                <!-- /.row -->
            </div>
        </section>
      
    </div>
    
    <aside class="control-sidebar control-sidebar-dark">
        
    </aside>
    
    <script src="../../plugins/jquery/jquery.min.js"></script>
    
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    
    <script src="../../dist/js/adminlte.min.js"></script>
    
    <script src="../../dist/js/demo.js"></script>
</body>
</html>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/istatistik/Partial1.cshtml
@model IEnumerable<TicariOtomasyonProjesi.Models.Siniflar.SinifGrup2>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayıları</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th> Bar</th>
                    <th style="width: 40px">Sayı</th>
                </tr>
            </thead>
            <tbody>
                @{ int sirano = 0;}
                @foreach (var x in Model)
                {


                    <tr>
                        <td>@{sirano++;} @sirano</td>
                        <td>@x.Departman</td>
                        <td>
                            @if (x.Sayi == 1)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.Sayi == 2)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                </div>
                            }
                            @if (x.Sayi >= 3)
                            {
                                <div class="progress progress-xs progress-striped active">
                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                </div>
                            }
                        </td>
                        <td>
                            @if (x.Sayi == 1)
                            {
                                <span class="badge bg-danger">@x.Sayi</span>
                            }
                            @if (x.Sayi == 2)
                            {
                                <span class="badge bg-warning">@x.Sayi</span>
                            }
                            @if (x.Sayi == 3)
                            {
                                <span class="badge bg-success">@x.Sayi</span>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/istatistik/Partial2.cshtml
@using TicariOtomasyonProjesi.Models.Siniflar
@model List<Cariler>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Cariler Hover Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ad</th>
                            <th>Soyad</th>
                            <th>Şehir</th>
                            <th>Mail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {


                            <tr>
                                <td>@x.Cariid</td>
                                <td>@x.CariAd</td>
                                <td>@x.CariSoyad</td>
                                <td>@x.CariSehir</td>
                                <td>@x.CariMail</td>
                                
                                
                               
                            </tr>


                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

TicariOtomasyonProjesi/TicariOtomasyonProjesi/Views/istatistik/Partial3.cshtml
@using TicariOtomasyonProjesi.Models.Siniflar
@model List<Urun>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Bilgi Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ürün Adı</th>
                            <th>Marka</th>
                            <th>Stok</th>
                            <th>Alış Fiyat</th>
                            <th>Satış Fiyat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {


                        <tr>
                            <td>@x.Urunid</td>
                            <td>@x.UrunAd</td>
                            <td>@x.Marka</td>
                            <td>@x.Stok</td>
                            <td>@x.AlisFiyat ₺</td>
                            <td>@x.SatisFiyat ₺</td>
                            
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            
        </div>
     
    </div>
</div>